### ISSUE TITLE
Request to add github action 

### ISSUE THREAD

**Issue by Jassi10000** [EddieHubCommunity/EddieBotBreakout#17]
@eddiejaoude  
This is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR too so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by Jassi10000** [comment]
@Cahllagerfeld Can you please add the hacktoberfest label to this

**Comment by Jassi10000** [comment]
@Cahllagerfeld The label got removed

**Comment by Vyvy-vi** [comment]
duplicate of #9

**Comment by Vyvy-vi** [comment]
closed by 9584505
