### ISSUE TITLE
[DOCS] <Add community.yml>

### ISSUE THREAD

**Issue by ezinneanne** [EddieHubCommunity/EddieBotBreakout#35]
### Adding community.yml
**Adding community.yml for the Github Action that sends the stats to the Eddiehub API**

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

We have decided to do this another way now, not with a GitHub Action as it fails on forks, but to try and do it via web hooks

I wil close this for now but you still get a green square 🤓
